name: Run demo
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: read-all
jobs:
  demo:
    name: Run demo 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout demo repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: gittuf/demo
      - name: Install Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
        with:
          python-version: '3.12'
      - name: Install gittuf-installer
        uses: gittuf/gittuf-installer@f6589511b7fb806ce365de81caa949b5c468089a
      - name: Run demo script
        run: python run-demo.py --no-prompt
